services:
  - type: static
    name: overmelhinho-app-staging
    repo: https://github.com/overmelhinho/overmelhinho.git
    branch: develop
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://overmelhinho-api-staging.onrender.com/api/v1
    redirects:
      - source: "/*"
        destination: "/index.html"
        statusCode: 200
