services:
  - type: web
    name: overmelhinho-api-staging
    env: docker
    rootDir: backend
    plan: free
    branch: develop
    buildCommand: ""
    startCommand: php artisan serve --host=0.0.0.0 --port=8080
    envVars:
      - key: APP_ENV
        value: staging
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://overmelhinho-api-staging.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: db.spefwgjsltjryxcizype.supabase.co
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        sync: false
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stderr
