services:
  - type: web
    name: overmelhinho-api-staging
    env: docker
    repo: https://github.com/overmelhinho/overmelhinho.git
    branch: develop
    dockerfilePath: backend/Dockerfile
    buildCommand: ""
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
    envVars:
      - key: APP_ENV
        value: staging
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: spefwgjsltjryxcizype.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: overmelhinho_staging
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        sync: false
