<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Supabase/Postgres fix: Garantir que a coluna ID seja identitária (auto-incremento)
        // O erro SQLSTATE[23502] indica que o Postgres está tentando inserir NULL no ID 
        // porque a coluna não tem um default (sequence/identity) associado.
        
        try {
            DB::statement("ALTER TABLE segmentos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY");
        } catch (\Exception $e) {
            // Se já for identity ou erro de permissão, ignoramos ou logamos
            report($e);
        }

        // Caso existam registros, precisamos sincronizar o contador da sequence
        $maxId = DB::table('segmentos')->max('id');
        if ($maxId) {
            $nextId = $maxId + 1;
            try {
                // Reinicia a sequence para o próximo ID disponível
                DB::statement("SELECT setval(pg_get_serial_sequence('segmentos', 'id'), $nextId, false)");
            } catch (\Exception $e) {
                // O pg_get_serial_sequence pode falhar se não for SERIAL, mas a IDENTITY acima deve resolver
            }
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        try {
            DB::statement("ALTER TABLE segmentos ALTER COLUMN id DROP IDENTITY IF EXISTS");
        } catch (\Exception $e) {
            //
        }
    }
};
